CREATE TABLE tcg_reference_catalog_state (
    catalog_name VARCHAR(100) PRIMARY KEY,
    source_digest VARCHAR(64) NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tcg_reference_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_tcg_reference_set_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE tcg_reference_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_set_id BIGINT NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    source_number VARCHAR(100) NOT NULL,
    normalized_collector_number VARCHAR(100) NOT NULL,
    CONSTRAINT fk_tcg_reference_card_set FOREIGN KEY (reference_set_id) REFERENCES tcg_reference_set (id),
    CONSTRAINT uk_tcg_reference_card_identity UNIQUE (
        reference_set_id,
        normalized_name,
        normalized_collector_number
    )
);

CREATE INDEX idx_tcg_reference_card_number
    ON tcg_reference_card (reference_set_id, normalized_collector_number);

CREATE INDEX idx_tcg_reference_card_name
    ON tcg_reference_card (reference_set_id, normalized_name);
