CREATE TABLE monitoring (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blueprint_id BIGINT NOT NULL,
    expansion_id BIGINT NOT NULL,
    card_name VARCHAR(255) NOT NULL,
    card_version VARCHAR(255) NOT NULL,
    expansion_name VARCHAR(255) NOT NULL,
    expansion_code VARCHAR(50) NOT NULL,
    language VARCHAR(10) NOT NULL,
    card_condition VARCHAR(50) NOT NULL,
    first_edition BOOLEAN NOT NULL,
    is_reverse BOOLEAN NOT NULL,
    graded BOOLEAN NOT NULL,
    signed BOOLEAN NOT NULL,
    altered BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_checked_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),
    CONSTRAINT chk_monitoring_blueprint_id CHECK (blueprint_id > 0),
    CONSTRAINT chk_monitoring_expansion_id CHECK (expansion_id > 0),
    CONSTRAINT chk_monitoring_currency CHECK (CHAR_LENGTH(currency) = 3)
);

CREATE INDEX idx_monitoring_active ON monitoring (active);

CREATE TABLE price_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitoring_id BIGINT NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    average_price_cents DECIMAL(19, 2),
    minimum_price_cents BIGINT,
    maximum_price_cents BIGINT,
    compatible_offers INTEGER NOT NULL,
    used_offers INTEGER NOT NULL,
    confidence VARCHAR(20) NOT NULL,
    CONSTRAINT fk_price_observation_monitoring
        FOREIGN KEY (monitoring_id) REFERENCES monitoring (id) ON DELETE CASCADE,
    CONSTRAINT chk_price_observation_currency CHECK (CHAR_LENGTH(currency) = 3),
    CONSTRAINT chk_price_observation_compatible_offers CHECK (compatible_offers >= 0),
    CONSTRAINT chk_price_observation_used_offers
        CHECK (used_offers >= 0 AND used_offers <= 5 AND used_offers <= compatible_offers),
    CONSTRAINT chk_price_observation_prices
        CHECK (
            (confidence = 'NO_DATA'
                AND average_price_cents IS NULL
                AND minimum_price_cents IS NULL
                AND maximum_price_cents IS NULL
                AND compatible_offers = 0
                AND used_offers = 0)
            OR
            (confidence IN ('LOW', 'MEDIUM', 'HIGH')
                AND average_price_cents IS NOT NULL
                AND minimum_price_cents IS NOT NULL
                AND maximum_price_cents IS NOT NULL
                AND average_price_cents >= 0
                AND minimum_price_cents >= 0
                AND maximum_price_cents >= minimum_price_cents
                AND used_offers BETWEEN 1 AND 5)
        )
);

CREATE INDEX idx_price_observation_monitoring_observed_at
    ON price_observation (monitoring_id, observed_at);
