CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT chk_app_user_username_length CHECK (CHAR_LENGTH(username) BETWEEN 3 AND 50)
);

INSERT INTO app_user (username, password_hash, enabled, created_at)
VALUES (
    '__legacy__',
    '$2a$10$7EqJtq98hPqEX7fNZaFWoO5v7NPrvQ8zu8JxvMpyR8i1oZbP9eW7W',
    FALSE,
    CURRENT_TIMESTAMP
);

ALTER TABLE monitoring ADD COLUMN owner_id BIGINT;

UPDATE monitoring
SET owner_id = (SELECT id FROM app_user WHERE username = '__legacy__')
WHERE owner_id IS NULL;

ALTER TABLE monitoring ALTER COLUMN owner_id SET NOT NULL;

ALTER TABLE monitoring ADD CONSTRAINT fk_monitoring_owner
    FOREIGN KEY (owner_id) REFERENCES app_user (id);

CREATE INDEX idx_monitoring_owner_active_created
    ON monitoring (owner_id, active, created_at);
