CREATE TABLE card_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expansion_id BIGINT NOT NULL,
    blueprint_id BIGINT NOT NULL,
    card_name VARCHAR(255) NOT NULL,
    card_version VARCHAR(255),
    collector_number VARCHAR(50) NOT NULL,
    image_source VARCHAR(50) NOT NULL,
    external_card_id VARCHAR(100),
    small_image_url VARCHAR(1000),
    large_image_url VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    verification_failures INTEGER NOT NULL DEFAULT 0,
    last_verified_at TIMESTAMP WITH TIME ZONE,
    verification_failed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_card_image_identity UNIQUE (
        expansion_id,
        blueprint_id,
        collector_number,
        image_source
    ),
    CONSTRAINT chk_card_image_blueprint_id CHECK (blueprint_id > 0),
    CONSTRAINT chk_card_image_expansion_id CHECK (expansion_id > 0),
    CONSTRAINT chk_card_image_status CHECK (status IN ('ACTIVE', 'REFRESH_NEEDED', 'BROKEN')),
    CONSTRAINT chk_card_image_verification_failures CHECK (verification_failures >= 0),
    CONSTRAINT chk_card_image_has_url CHECK (small_image_url IS NOT NULL OR large_image_url IS NOT NULL)
);

CREATE INDEX idx_card_image_lookup
    ON card_image (expansion_id, blueprint_id, collector_number, image_source);

CREATE INDEX idx_card_image_status_verified
    ON card_image (status, last_verified_at);
