alter table app_user add column telegram_chat_id varchar(50);
alter table app_user add column telegram_username varchar(255);
alter table app_user add column telegram_enabled boolean not null default false;
alter table app_user add column telegram_linked_at timestamp with time zone;
alter table app_user add column telegram_last_error varchar(1000);

create table telegram_link_request (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(64) not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    used_at timestamp with time zone,
    constraint fk_telegram_link_request_user
        foreign key (user_id) references app_user(id),
    constraint uk_telegram_link_request_token unique (token)
);

create index idx_telegram_link_request_user_created
    on telegram_link_request(user_id, created_at desc);
