CREATE TABLE collection_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expansion_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL,
    card_count INTEGER NOT NULL DEFAULT 0,
    image_sync_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    image_sync_started_at TIMESTAMP WITH TIME ZONE,
    image_sync_completed_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_collection_set_expansion UNIQUE (expansion_id),
    CONSTRAINT chk_collection_set_expansion_id CHECK (expansion_id > 0),
    CONSTRAINT chk_collection_set_card_count CHECK (card_count >= 0),
    CONSTRAINT chk_collection_set_image_sync_status
        CHECK (image_sync_status IN ('NOT_STARTED', 'RUNNING', 'COMPLETED', 'PARTIAL_FAILED'))
);

CREATE TABLE collection_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_set_id BIGINT NOT NULL,
    expansion_id BIGINT NOT NULL,
    blueprint_id BIGINT NOT NULL,
    card_name VARCHAR(255) NOT NULL,
    card_version VARCHAR(255) NOT NULL,
    collector_number VARCHAR(50),
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_collection_card_set
        FOREIGN KEY (collection_set_id) REFERENCES collection_set (id) ON DELETE CASCADE,
    CONSTRAINT uk_collection_card_identity UNIQUE (expansion_id, blueprint_id),
    CONSTRAINT chk_collection_card_expansion_id CHECK (expansion_id > 0),
    CONSTRAINT chk_collection_card_blueprint_id CHECK (blueprint_id > 0),
    CONSTRAINT chk_collection_card_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_collection_card_set_order
    ON collection_card (collection_set_id, sort_order);

CREATE TABLE user_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    collection_set_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_collection_owner
        FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_collection_set
        FOREIGN KEY (collection_set_id) REFERENCES collection_set (id),
    CONSTRAINT uk_user_collection_owner_set UNIQUE (owner_id, collection_set_id)
);

CREATE INDEX idx_user_collection_owner_active
    ON user_collection (owner_id, active, created_at);

CREATE TABLE user_collection_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_collection_id BIGINT NOT NULL,
    collection_card_id BIGINT NOT NULL,
    owned BOOLEAN NOT NULL DEFAULT FALSE,
    owned_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_collection_card_collection
        FOREIGN KEY (user_collection_id) REFERENCES user_collection (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_collection_card_card
        FOREIGN KEY (collection_card_id) REFERENCES collection_card (id),
    CONSTRAINT uk_user_collection_card_identity UNIQUE (user_collection_id, collection_card_id)
);

CREATE INDEX idx_user_collection_card_collection
    ON user_collection_card (user_collection_id);
